### PR TITLE
Add DataFusion Python docs

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Review by martin-g — APPROVED** [review]
LGTM

**Comment by kou** [comment]
How about using apache/arrow-datafusion-python and `.asf.yaml` instead of pushing this to apache/arrow-site like apache/arrow-cookbook and https://arrow.apache.org/cookbook/ ?
If we this approach, we don't need https://github.com/apache/arrow-site/pull/278 .

See also:
  * `.asf.yaml` document for publishing to https://arrow.apache.org/ : https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Publishingabranchtoyourprojectwebsite
    * apache/arrow-cookbook's `.asf.yaml` configuration: https://github.com/apache/arrow-cookbook/blob/main/.asf.yaml#L32-L34
  * The `asf-site` branch that is published to https://arrow.apache.org/cookbook/ : https://github.com/apache/arrow-cookbook/tree/asf-site 
  * The GitHub Action job that publish to the `asf-site` branch automatically: https://github.com/apache/arrow-cookbook/blob/main/.github/workflows/deploy_cookbooks.yml#L71-L101

**Comment by andygrove** [comment]
Thanks @kou. I did not realize this was an option. I will use this approach instead of creating PRs here :rocket:

**Comment by andygrove** [comment]
@kou I am not sure how we use GitHub Actions here to only publish the docs after the release is voted on. We would not want to push the docs on every change to master since the docs are for the released version. I guess this is a different use case compared to arrow cookbook. Are you OK with us continuing with the manual process of creating PRs here for each release?

**Comment by martin-g** [comment]
You could use git tags.
I.e. the workflow should run only when there is a push to tag like "v0.8.0"

**Comment by kou** [comment]
> @kou I am not sure how we use GitHub Actions here to only publish the docs after the release is voted on.

apache/arrow-datafusion-python uses `X.Y.Z-rcN` tag for RC and uses `X.Y.Z` tag for approved release, right?
Then how about using the following configuration to update the `asf-site` branch?

```yaml
on:
  push:
    branches-ignore:
      - '**'
    tags-ignore:
      - '*-rc*'

jobs:
  ...
```

If you want, I can open a pull request to apache/arrow-datafusion-python. (@martin-g may be able to implement it too. :-)

> Are you OK with us continuing with the manual process of creating PRs here for each release?

Sure if you like this approach.

**Comment by martin-g** [comment]
> @martin-g may be able to implement it too

Sure! Just let me know! :-)

**Comment by andygrove** [comment]
Thanks @martin-g and @kou  ... I will take all the help I can get with this. @martin-g do you want to open a PR and perhaps @kou can review? Thanks again for the help with this.

**Comment by martin-g** [comment]
Let me try it!

**Comment by martin-g** [comment]
One can use also https://arrow.staged.apache.org/datafusion-python/ to see the docs for current `master` branch that will be released with the next version.

Thank you for your help, @kou !

**Pull request closed without merging**
