### PR TITLE
[Website] Update documentations for 18.1.0

### PR DESCRIPTION
**Pull request by amoeba**

### CODE REVIEW

**Comment by amoeba** [comment]
I tested this out locally and it doesn't look quite right. I expected to find an `18.0` folder but it's not here:

```
$ ls -1 | grep -P "^\d"
1.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
16.1
17.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
```

Looking into it.

**Comment by amoeba** [comment]
I removed the `is_major_version` conditionals from post-10-docs.sh locally so the script runs the same for majors as well as minors and the 18.0 folder is now present. @assignUser do you have any thoughts on whether this is the right fix? The conditionals were added quite a long time ago so maybe I'm missing something. cc @raulcd

**Review by raulcd — APPROVED** [review]
GitHub diff does not show that  `/docs` are also updated with the new version.

From what I can see `16.0` had to be re-added so good to do the copy here:
- https://github.com/apache/arrow-site/pull/555

We probably want to fix `post-10-docs.sh` to instead of removing the `is_major_version` checks, check if `is_patch_version` and avoid copying on those cases

**Comment by amoeba** [comment]
Thanks @raulcd, just to check, when you say,

> GitHub diff does not show that  /docs are also updated with the new version.

Did you mean that the diff _does_ show the docs are updated? When I look at the diff, I see changes like,

```patch
diff --git a/docs/python/api.html b/docs/python/api.html
index 66f486d69e0..4d4dd1cbe22 100644
--- a/docs/python/api.html
+++ b/docs/python/api.html
@@ -9,7 +9,7 @@
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="generator" content="Docutils 0.19: https://docutils.sourceforge.io/" />

-    <title>API Reference &#8212; Apache Arrow v18.0.0</title>
+    <title>API Reference &#8212; Apache Arrow v18.1.0</title>
```

which I interpret as the docs being updated with the new version (18.1.0).

**Comment by raulcd** [comment]
Yes, sorry for the confusion. I meant that there are so many files that the GitHub diff doesn't show properly. I validated the branch and all looks good. It can be merged.

**Comment by amoeba** [comment]
Awesome, thanks. I'll file an issue about re-working post-10-docs.sh for the 19.0.0 release.

**Pull request merged**
