### PR TITLE
Add Daniël Heres to list of PMC

### PR DESCRIPTION
**Pull request by alamb**
See mailing list thread: https://lists.apache.org/thread/ntx3251pwnbd759kghbyjn4s31kcf8v2

cc @Dandandan

### CODE REVIEW

**Review by Dandandan — APPROVED** [review]
🎉 thanks @alamb

**Comment by alamb** [comment]
cc @nealrichardson

**Review by kou — APPROVED** [review]
+1

@alamb Could you use your fork instead of apache/arrow-site next time? Our CI job doesn't expect to create a feature branch in apache/arrow-site.

**Comment by alamb** [comment]
> @alamb Could you use your fork instead of apache/arrow-site next time? Our CI job doesn't expect to create a feature branch in apache/arrow-site.

Will do -- sorry about that @kou

**Pull request merged**
