### PR TITLE
ARROW-6616: [Website] Release announcement blog post for 0.15

### PR DESCRIPTION
**Pull request by nealrichardson**
Needs filling in. Any committers should feel free to edit and push to my fork with changes.

### CODE REVIEW

**Comment by pitrou** [comment]
Someone should add the Tensor updates. @mrkn

**Comment by wesm** [comment]
I will review and update with details when I can. We don't have a release candidate yet so there is time

**Comment by shiro615** [comment]
I've added Ruby and C GLib notes.

**Comment by wesm** [comment]
I'm working on this branch to get it closer to publication-readiness. I'll update it later tonight or tomorrow

**Comment by wesm** [comment]
Merged. Thank you

**Pull request closed without merging**
