### PR TITLE
Website: Fix stable banner for 15.0.1

### PR DESCRIPTION
**Pull request by raulcd**
I did run:
```
$ find ./ -type f -exec sed -i "s/DOCUMENTATION_OPTIONS.show_version_warning_banner = true/DOCUMENTATION_OPTIONS.show_version_warning_banner = false/g" {} \;
$ cd 14.0/
$ git restore .
$ cd ../dev/
$ git restore .
```

### CODE REVIEW

**Comment by raulcd** [comment]
@AlenkaF your fix is supposed to work with the next major releases but it did not work for the minor release :) 
I had to manually run the fix.

**Comment by AlenkaF** [comment]
Oh, too bad.

If I understand correctly, the change added here: https://github.com/apache/arrow/pull/39762 also affects the docs being built for minor releases but since these are not moved to a separate folder they should not include the change - neither `DOCUMENTATION_OPTIONS.theme_switcher_version_match` nor
`DOCUMENTATION_OPTIONS.show_version_warning_banner`.

The first change, `DOCUMENTATION_OPTIONS.theme_switcher_version_match`, is also necessary I think because when the current stable docs will be copied to a subfolder (`15.0`) the version displayed on the banner will currently be `15.0.1` instead for `15.0`.


I guess we need to add something like `if [ "$is_major_release" = "yes" ] ; then [...] fi` to the code we added in https://github.com/apache/arrow/pull/39762. Will make an issue and a PR for it, if my understanding is correct.

**Comment by raulcd** [comment]
> I guess we need to add something like `if [ "$is_major_release" = "yes" ] ; then [...] fi` to the code we added in [apache/arrow#39762](https://github.com/apache/arrow/pull/39762). Will make an issue and a PR for it, if my understanding is correct.

Sounds good, the if is necessary also because `previous_series` is not defined for non major releases.

**Comment by raulcd** [comment]
:+1:

**Pull request merged**
