### PR TITLE
[Website] Update documentations for 7.0.0

### PR DESCRIPTION
**Pull request by kszucs**
I had to manually restore the docs for the latest 6.0 release since we only restore the versioned directories in the [post release script](https://github.com/apache/arrow/blob/master/dev/release/post-09-docs.sh#L47) but the latest docs are stored in the docs root `arrow-site/docs/` directory instead of `arrow-site/docs/<version>` subdirectory. 

@jorisvandenbossche could you please take a look at both this PR and the docs release script?

### CODE REVIEW

**Comment by kou** [comment]
Ah, we need to update `post-09-docs.sh` to do the followings:

1. Keep `docs/dev/` like `docs/*.0/`.
2. Move `docs/` except `docs/{dev,*.0}/` to `docs/X.Y/`.

**Comment by jorisvandenbossche** [comment]
For the other "old" versions, I removed the `/java/reference` folder to reduce the size (that folder is little over 100MB, more than half of the size of the full docs). We should maybe do that for the docs moved to `/6.0` as well.

I can take a look at updating the script next week.

**Comment by jorisvandenbossche** [comment]
I opened https://github.com/apache/arrow/pull/12355 for some edits to the release script, and opened https://github.com/apache/arrow-site/pull/189 with the result of the new script as an alternative for this PR.

**Comment by kou** [comment]
I close this in favor of #189.

**Pull request closed without merging**
