### PR TITLE
Update docs versions.json

### PR DESCRIPTION
**Pull request by thisisnic**
The R docs versions.json file was not updated during the release - this PR adds the changes which the release script should have generated.

### CODE REVIEW

**Comment by nealrichardson** [comment]
Note that the other old version docs are in x.y directories (e.g. 6.0) but the last release is 7.0.0: https://github.com/apache/arrow-site/tree/asf-site/docs/7.0.0

So we need to `git mv docs/7.0.0 docs/7.0` for this to not have broken links (and we probably need to fix the script that puts it there for the future).

**Comment by jorisvandenbossche** [comment]
Yes, good catch, just renamed those. So that's another thing to fix in the release script

**Comment by nealrichardson** [comment]
> Yes, good catch, just renamed those. So that's another thing to fix in the release script

Do we have a JIRA yet for that?

**Comment by jorisvandenbossche** [comment]
I was looking for a mistake in the PR I made for this (https://github.com/apache/arrow/pull/12355), but so it's actually how you invoke the script, and that is currently not in the Arrow source code, but in the confluence wiki (we should maybe consider to move that to our development docs)

**Review by nealrichardson — APPROVED** [review]
I can't verify the version.json changes because I think a URL is hard-coded to the arrow site, but the change looks right.

**Comment by nealrichardson** [comment]
Confirmed that the deploy looks good

**Comment by kou** [comment]
It seems that we should have removed patch version from `previous_version` here: https://github.com/apache/arrow/pull/12355/files#diff-ae6e7dcbd5646d2ecbed30d2c82bec3c6e8bb47271280aa1795f7a3455172e7dR84

```bash
   mv docs_temp docs/$(echo ${previous_version} | sed -e 's/^\([0-9]*\.[0-9]*\)\..*$/\1/')
```

**Comment by jorisvandenbossche** [comment]
We can remove it in the script, but that's the only thing it is used for, so we could also document to use the script with passing it the shorter name (although handling it in the script will probably be more robust to avoid exactly what we had here ;))

**Pull request merged**
