### PR TITLE
MINOR: [Website] Add datafusion to homepage top banner

### PR DESCRIPTION
**Pull request by houqp**
Following the advice from https://lists.apache.org/thread.html/r5c9341fe5360ae249532724da2bf92bd2ed661d1c58f599212e82107%40%3Cdev.arrow.apache.org%3E.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
We might not want it at the actual top-level in the header, I think (there are no other specific implementations listed there). Maybe you can put it in the dropdown list items of "Documentation" ?

**Comment by houqp** [comment]
Hi @jorisvandenbossche , thanks for the review. For clarification, datafusion is not a specific implementation of Arrow, but a self-contained query engine built on top of arrow's rust implementation. We actually started with adding Datafusion docs into the current Arrow documentation. But we were given feedback that Datafusion shouldn't be included in the current documentation because it's not an implementation, see: https://github.com/apache/arrow/pull/10982#issuecomment-908335511. Following that feedback, I intentionally moved it out of the documentation dropdown to avoid confusions.

**Comment by jorisvandenbossche** [comment]
Yeah, sorry about the imprecise phrasing. I know datafusion is not a specific language implementation of Arrow (and thus it might not fit in the list of languages), but it's still a library implemented on top of Arrow, and so we also currently don't list any specific library in the top-level header. Space in the top-level header is scarce, so we should be cautious with adding content there.

I still think it can fit under the Documentation dropdown, but maybe can put another horizontal line between the languages, and then datafusion as a library.

**Comment by kszucs** [comment]
Agree with Joris, later on we can create a `Query Engines` dropdown or something like that. 

Eventually we're going to have plenty of libraries around the arrow specs so we should probably have a table somewhere highlighting more details about the libraries.

**Comment by houqp** [comment]
I see, thanks for the clarification, it makes sense to me. How about we create a query engine or subproject drop down now? I am also expecting to see more subproject popping up within Arrow. That said, I don't have a strong opinion on this, if you all think it's better to put it under the documentation dropdown, I would be more than happy to do so.

**Comment by wesm** [comment]
Having a "subprojects" dropdown seems okay to me

**Comment by houqp** [comment]
Alright, pushed an update to move datafusion into a new subprojects dropdown :)

**Review by kszucs — APPROVED** [review]
Thanks @houqp!

**Pull request merged**
