### PR TITLE
Website: Release 14.0.2 blog post

### PR DESCRIPTION
**Pull request by raulcd**
Release blog post for 14.0.2

### CODE REVIEW

**Comment by raulcd** [comment]
@jorisvandenbossche @kou should we add a release blog post for the release? Do we want to expand the issues that have been solved or should we just point to the changelog (as there aren't that many issues there):
https://arrow.apache.org/release/14.0.2.html#changelog

**Comment by kou** [comment]
Which issue did trigger 14.0.2? How about just mentioning it explicitly in the blog post?

**Comment by jorisvandenbossche** [comment]
Given it's relatively short, the changelog might be sufficient? (although not all PR titles are very descriptive ..) I can also make a human summary of the fixes later today if that is preferred.

**Comment by jorisvandenbossche** [comment]
This would be something like the following (I haven't checked all [R] labeled issues in detail, I am not sure if there is anything worth mentioning, or whether they are mostly CI fixes xx @assignUser)

Python:

* Delay initializing the S3 filesystem until first usage (instead on import) ([GH-38364](https://github.com/apache/arrow/issues/38364))
* Fix segfault when PyArrow is imported at shutdown ([GH-38626](https://github.com/apache/arrow/issues/38626))
* Fix potential deadlock when CSV reading errors out ([GH-38676](https://github.com/apache/arrow/issues/38676))

C++:
* S3FileSystem: fix regression in deleting explicitly created sub-directories ([GH-38618](https://github.com/apache/arrow/issues/38618))

Parquet (C++):
* Fix performance regression in reading binary/string columns ([GH-38432](https://github.com/apache/arrow/issues/38432))
* Fix regression in reading Parquet files in parallel ([GH-38432](https://github.com/apache/arrow/issues/38432))
* Fix bug in reading valid Parquet files written with older versions ([GH-38577](https://github.com/apache/arrow/issues/38577))

**Comment by raulcd** [comment]
Thanks @jorisvandenbossche I've pushed a commit with the suggested notes: e4207732a156c3df0ce85ac6e646b7ebf3bff599

**Review by raulcd — COMMENTED** [review]
:+1:

**Review by jorisvandenbossche — APPROVED** [review]

**Review by kou — APPROVED** [review]
+1

**Comment by assignUser** [comment]
Sorry for the late reply, most/all changes for arrow R where fixes for 14.0.0 build system refactor related  issues. I can open a PR in a bit (on PTO for now)

**Pull request merged**
