### PR TITLE
[Website] Add release note for 10.0.0

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Review by kou — COMMENTED** [review]
+1

**Comment by lidavidm** [comment]
I don't think it got deployed, because it wasn't yet October 31st in CI's time zone: https://github.com/apache/arrow-site/actions/runs/3357933086/jobs/5564218467#step:9:39

```
      Generating... 
          Skipping: _posts/2022-10-31-10.0.0-release.md has a future date
       Jekyll Feed: Generating feed for posts
```

**Comment by kou** [comment]
Good catch!
I re-ran the task and this post has been published: https://arrow.apache.org/blog/2022/10/31/10.0.0-release/

**Comment by lidavidm** [comment]
thank you! and sorry, I forgot I could just do that myself :sweat_smile:

**Pull request merged**
