### PR TITLE
[Website] Release docs 18.0.0

### PR DESCRIPTION
**Pull request by amoeba**

### CODE REVIEW

**Comment by amoeba** [comment]
This PR looks better than my last now that the issue with the docs script has been fixed locally.

@raulcd can you verify it's okay that the version switcher still shows 17.0.0 when I preview this locally? I think this can be merged if that's okay.

**Comment by kou** [comment]
Could you update it with https://github.com/apache/arrow/blob/main/docs/source/_static/versions.json manually for now?

**Comment by amoeba** [comment]
Done in https://github.com/apache/arrow-site/pull/553/commits/a95c937a21e5bd28aba421d6db683d6a258476cc. I previewed it locally and it looks good (switcher now shoes 18.0.0 as stable).

**Comment by amoeba** [comment]
As for why it wasn't updated, it looks like the docs uploaded to jfrog didn't get the new versions.json:

```
bryce@debian:~/Downloads$ wget https://apache.jfrog.io/artifactory/arrow/docs/18.0.0/docs.tar.gz
bryce@debian:~/Downloads$ tar xzf docs.tar.gz 
bryce@debian:~/Downloads$ head docs/_static/versions.json 
[
    {
        "name": "18.0 (dev)",
        "version": "dev/",
        "url": "https://arrow.apache.org/docs/dev/"
    },
    {
        "name": "17.0 (stable)",
        "version": "",
        "url": "https://arrow.apache.org/docs/",
```

**Comment by kou** [comment]
We need to investigate it. Could you open an issue for it on apache/arrow?

**Review by kou — APPROVED** [review]
+1

**Comment by amoeba** [comment]
Done: https://github.com/apache/arrow/issues/44574.

**Pull request merged**
