### PR TITLE
ARROW-12356: [Website] Update install page instructions to point to artifactory

### PR DESCRIPTION
**Pull request by nealrichardson**
Disclaimer: I did not test that these work, just find-replaced the URLs.

There are more bintray URLs on the per-release pages (which I believe are created automatically as a post-release task), but I don't know how to begin to fix those.

### CODE REVIEW

**Comment by kou** [comment]
Unfortunately, this doesn't work.
apache-arrow-archive-keyring and apache-arrow-release install APT/Yum repository configurations but Bintray URL exists in the configurations...
We can use `sed -i'' -e 's,https://apache.bintray.com/,https://apache.jfrog.io/artifactory/,g' /etc/apt/sources.list.d/apache-arrow.sources` or something as a workaround to use the current apache-arrow-archive-keyring and apache-arrow-release. If Artifactory upload isn't ready by Bintray close, we'll use the workaround.

**Comment by nealrichardson** [comment]
Well bintray is already doing brownouts now and we're getting reports about it. Either way we'll need to do something like this for past releases right? (Or maybe we don't care about that?)

**Comment by kou** [comment]
> for past releases

You mean that users who already installed 3.0.0 or earlier need to do something like this, right?

Yes. They need to update repository URL manually. They need to do one of the followings:

  * `sed -i'' -e 's,https://apache.bintray.com/,https://apache.jfrog.io/artifactory/,g' /etc/apt/sources.list.d/apache-arrow.sources` for APT users
  * `sed -i'' -e 's,https://apache.bintray.com/,https://apache.jfrog.io/artifactory/,g' /etc/yum.repos.d/Apache-Arrow.repo` for Yum users
  * Install `apache-arrow-apt-source`/`apache-arrow-release` 4.0.0 or later

We can advertise apache.jfrog.io/artifactory URL with `sed ...` workaround now. We can update the install instructions when we release `apache-arrow-apt-source`/`apache-arrow-release` 4.0.0.

Do you want me to add the workarounds to this branch?

**Comment by nealrichardson** [comment]
@kou it would be great if you could do that. I don't know enough about the details so I'd just be pasting in whatever you told me.

**Comment by kou** [comment]
I noticed that metadata for Yum repositories aren't copied to Artifactory from Bintray...
So we can't use Artifactory for CentOS and Amazon Linux for now.

Anyway, I've updated the current instructions.

**Review by kszucs — APPROVED** [review]

**Pull request merged**
