### PR TITLE
[Website] Update documentations for 9.0.0

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Looks good based on a quick look!

One comment: can you rename the 8.0.0 directory to 8.0 ? 
(and is that something we have to update in the script that creates this?)

**Comment by kszucs** [comment]
Could someone do the rename? I'm currently away from keyboard.

**Comment by kou** [comment]
Can we always use `MAJOR.MINOR` for this?
Then, we can normalize the version at https://github.com/apache/arrow/blob/master/dev/release/post-08-docs.sh#L33 in this script.

**Comment by jorisvandenbossche** [comment]
Indeed, that's something we should update in the release script

**Comment by jorisvandenbossche** [comment]
Indeed, that's something we can update in the release script. Since this is passed by the person calling this script, we can also document that you need to pass the normalized version. But checking for this in the script or automatically normalizing anyway will be probably be better to prevent future mistakes.

**Comment by kou** [comment]
Yes.
I like auto normalization approach.

**Comment by kou** [comment]
ARROW-17317

**Pull request merged**
