### PR TITLE
ARROW-6569: [Website] Add support for auto deployment by GitHub Actions

### PR DESCRIPTION
**Pull request by kou**
This may have an issue for GitHub Pages deploy for forks. But this
will be fixed by GitHub:

https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869

### CODE REVIEW

**Comment by kou** [comment]
Example: https://kou.github.io/arrow-site/index.html

Note that https://kou.github.io/arrow-site/ isn't available. :<

**Comment by nealrichardson** [comment]
https://kou.github.io/arrow-site/ works for me (now) so maybe whatever the problem was is fixed?

If it works, then I'm +1 on the change. I'd just ask that you update the README to note this change and update the instructions there (remove the stuff about deploy keys and PATs, at minimum). Also, is there any setup required to make this work? Do I have to do something to enable github actions on my fork? Do we have to do something to enable it on apache/arrow-site? Are you certain we are permitted to do that on apache/arrow-site?

**Comment by wesm** [comment]
@nealrichardson it appears that GitHub Actions may allow us to benefit from the capabilities of Azure Devops without having to jump through hoops with ASF Infra (previously we've been unable to use it because of repo permissions issue -- Azure Devops / Pipelines require that their app have write access to the repo)

**Comment by kou** [comment]
I've removed all automatic deployment document from README. Because we don't need to do nothing.
This GitHub Action runs on apache/arrow-site. So contributors need to do nothing. apache/arrow-site is already GitHub Actions ready.

I'm also adding a step to this GitHub Action to comment preview GitHub Pages URL. If we don't have this, we need to describe preview URL in README.

It doesn't work yet. I'll leave a comment here when it works.

**Comment by kou** [comment]
Worked: https://github.com/kou/arrow-site/pull/2#issuecomment-531978279

**Comment by kou** [comment]
No objection.
I'll merge this.

**Pull request merged**
