### PR TITLE
ARROW-11486: [Website] Use Jekyll 4 and webpack to support Ruby 3.0 or later

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
Preview: https://kou.github.io/arrow-site/

**Comment by nealrichardson** [comment]
That's a really big diff, is that expected?

**Comment by kou** [comment]
Yes. But this may be overkill because this also includes Ruby 3.1 (this is not released yet. I'm building it from Git repository.) support.

If we like a small diff, adding `gem "webrick"` to `Gemfile` will be enough.

jekyll-assets depends on Nokogiri (an XML parser library for Ruby). It doesn't work with Ruby 3.1. (It's a Bundler's (package manager for Ruby) problem not Nokogiri.)

jekyll-assets isn't maintained well and we can drop jekyll-assets dependency by upgrading Jekyll to 4 from 3. Jekyll 4 has built-in SCSS support. This pull request includes Jekyll upgrade.

And this pull request also changes CSS/JavaScript management method to webpack from RubyGems.

Should we split this pull request to 1) just supporting Ruby 3.0 and 2) upgrading Jekyll to remove jekyll-assets dependency?

**Comment by kou** [comment]
Does anyone want to review this?
If nobody wants to do, I'll merge this.

**Review by nealrichardson — CHANGES_REQUESTED** [review]
Thanks for doing this and for the explanation of the changes. I think you should change the title of the JIRA since you're upgrading much more than the Ruby version supported. 

Can you please also update the instructions on the README for how to build and serve? I think they're out of date with this change. Other than that, LGTM!

**Comment by kou** [comment]
It makes sense!

Done.

**Review by nealrichardson — APPROVED** [review]
Thanks again!

**Comment by kou** [comment]
I'll merge this.

**Pull request closed without merging**
