### PR TITLE
[Website] Update documentations for 16.0.0

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@AlenkaF from my understanding this commit is good: https://github.com/apache/arrow-site/pull/499/commits/1b6cec9d1ce9737ff127ef070169c4fbb8a94dbd
and we can merge.

**Comment by AlenkaF** [comment]
> @AlenkaF from my understanding this commit is good: [1b6cec9](https://github.com/apache/arrow-site/commit/1b6cec9d1ce9737ff127ef070169c4fbb8a94dbd) and we can merge.

Yes, the changes (`'15.0.0'` for `theme_switcher_version_match` and `true` for `show_version_warning_banner`) are correct 👍

**Comment by kou** [comment]
OK. Let's try.

**Comment by kou** [comment]
Hmm.

@AlenkaF Do you know what is missing...?

**Pull request merged**
